Log started at 2025-04-17T18-10-43-040Z
2025-04-17T18:11:37.023Z - ERROR: Directus Error: Value for field "id" in collection "organization_addresses" has to be unique. (Status: 400) {"collection":"organization_addresses","field":"id","code":"RECORD_NOT_UNIQUE"} Context: {}
2025-04-17T18:11:44.840Z - ERROR: Directus Error: select `organization_addresses`.`id`, `organization_addresses`.`sort`, `organization_addresses`.`user_created`, `organization_addresses`.`date_created`, `organization_addresses`.`user_updated`, `organization_addresses`.`date_updated`, `organization_addresses`.`name`, `organization_addresses`.`address_type`, `organization_addresses`.`address_line_1`, `organization_addresses`.`address_line_2`, `organization_addresses`.`city`, `organization_addresses`.`state`, `organization_addresses`.`postal_code`, `organization_addresses`.`country`, `organization_addresses`.`organization`, st_astext(`organization_addresses`.`geo_location`) as `geo_location` from `organization_addresses` where (`organization_addresses`.`id` in ('50ee1911-8290-48bf-a7be-0bc0b380bd34')) order by `organization_addresses`.`sort` asc limit 1 - SQLITE_ERROR: no such function: st_astext (Status: 500) {"code":"INTERNAL_SERVER_ERROR"} Context: {}
2025-04-17T18:11:45.173Z - ERROR: Directus Error: select `organization_addresses`.`id`, `organization_addresses`.`sort`, `organization_addresses`.`user_created`, `organization_addresses`.`date_created`, `organization_addresses`.`user_updated`, `organization_addresses`.`date_updated`, `organization_addresses`.`name`, `organization_addresses`.`address_type`, `organization_addresses`.`address_line_1`, `organization_addresses`.`address_line_2`, `organization_addresses`.`city`, `organization_addresses`.`state`, `organization_addresses`.`postal_code`, `organization_addresses`.`country`, `organization_addresses`.`organization`, st_astext(`organization_addresses`.`geo_location`) as `geo_location` from `organization_addresses` where (`organization_addresses`.`id` in ('64106282-2b39-45f6-99a9-643de04103be')) order by `organization_addresses`.`sort` asc limit 1 - SQLITE_ERROR: no such function: st_astext (Status: 500) {"code":"INTERNAL_SERVER_ERROR"} Context: {}
